from .database import SessionLocal, engine, Base
from app import models, schemas, crud
import random

# Create the session and the database
Base.metadata.create_all(bind=engine)
db = SessionLocal()

# Predefined data
categories = [
    "Carnes",
    "Suínos",
    "Frangos",
    "Peixes",
    "Hortifrutis",
    "Padaria",
    "Grãos e Cereais",
    "Bebidas",
    "Limpeza e Higiene",
    "Congelados",
    "Doces",
    "Pet",
    "Biscoitos",
]

# Real brand names
real_brands = [
    "SEM MARCA", "Oreo", "Nestlé", "Trakinas", "Mabel",
    "Marilan", "Passatempo", "Bauducco", "Bono", "Piracanjuba",
    "Parmalat", "Coca-Cola", "Pepsi", "Guaraná Antarctica",
    "Schweppes", "Fanta", "Dr Pepper", "Mineral",
    "São Lourenço", "Indaiá", "Crystal", "Leão",
    "Del Valle", "Kapo", "Vô Luiz", "Nesquik", "Toddynho",
    "Nescau", "Molico", "Ovomaltine", "Cristal", "União",
    "Da Barra", "Pilão", "3 Corações", "Melitta", "Pelé",
    "Nespresso", "Vigor", "Danone", "Batavo", "Itambé",
    "Kellogg's", "Quaker", "Sadia", "Perdigão", "Aurora",
    "Texas", "Pif Paf", "Seara", "Friboi", "Arcor",
    "Kopenhagen", "Cacau Show", "Garoto", "Lacta",
    "Skol", "Brahma", "Antarctica", "Heineken",
    "Budweiser", "Corona", "Red Bull", "Monster",
    "Burn", "Fusion", "H2OH!", "Taurus", "Tio João",
    "Combrasil", "Kicaldo", "Renata", "Adria", "Arezzo",
    "Lux", "Granado", "O Boticário", "Phebo", "Head & Shoulders",
    "Pantene", "Garnier", "L'Oreal", "TRESemmé", "Nivea",
    "Neve", "Scott", "Personal", "Pedigree", "Royal Canin",
    "Premier", "Papadog", "Whiskas", "Camil", "Qualitá",
    "Soya", "Liza", "Cisne", "Maggi", "Sazón", "Arisco",
    "Fubá","Santa Tereza", "Dona Benta", "Santo Antônio",
    "Yoki", "Kibon", "Ben & Jerry's", "Tixan", "Veja",
    "Omo", "Brilhante", "Surf", "Comfort",
    "Downy", "Ypê", "Dove", "Minuano", "Assolan",
    "Limpol", "Cif", "Nissin", "Wickbold",
    "Plus Vita", "Panco", "Seven Boys",
    "Qualy", "Doriana", "Becel", "Delícia",
    "Claybom", "Président", "Colgate",
    "Oral-B", "Close-Up"
]


supermarkets = [
    {"name": "JPavani", "address": "R. Evaldo Costa, 100 - Sol e Mar, Macaé - RJ, 27940-410"},
    {"name": "Supermarket", "address": "Av. Rui Barbosa, 1030 - Alto dos Cajueiros, Macaé - RJ, 27915-012"},
    {"name": "São José", "address": "R. Teixeira de Gouveia, 1693 - Centro, Macaé - RJ, 27916-000"},
    {"name": "Extra Centro", "address": "R. Silva Jardim, 505 - Centro, Macaé - RJ, 27910-340"},
    {"name": "Machado", "address": "R. Alcides Mourão, 314 - Aroeira, Macaé - RJ, 27945-402"},
    {"name": "Extra Riviera", "address": "Av. Carlos Augusto T. Garcia - Riviera Fluminense, Macaé - RJ, 27937-590"},
    {"name": "Nova Esperança", "address": "Av. Dr. Humberto de Queiroz Matoso, 152 - Sol e Mar, Macaé - RJ, 27940-700"},
    {"name": "Por do Sol", "address": "R. Tenente-Coronel Amado, 330 - Centro, Macaé - RJ, 27910-070"},
    {"name": "Carrefour", "address": "R. Bento Pessanha, 800 - Loja 01 - Glória, Macaé - RJ, 27937-004"},
    {"name": "Assaí", "address": "Avenida Lacerda, R. Elías Agostinho, 2175 - Virgem Santa, Macaé - RJ, 27930-070"},
    {"name": "Motiva Novo Visconde", "address": "R. Pref. Antônio Curvelo Benjamin, 535 - Visconde de Araújo, Macaé - RJ, 27940-390"},
    {"name": "Dom", "address": "RJ-106, 2885 - Fronteira, Macaé - RJ, 27961-214"},
    {"name": "Atacadão", "address": "RJ-106, 106 - São José do Barreto, Macaé - RJ, 27971-130"},
    {"name": "Hortifruti", "address": "R. Ver. Manoel Braga, 83 - Centro, Macaé - RJ, 27910-350"},
]

# Products list
products = [
    {'name': 'Acém 1kg', 'category_id': 1, 'brand_id': 1, 'price': 2940},
    {'name': 'Acém 1kg', 'category_id': 1, 'brand_id': 51, 'price': 3290},
    {'name': 'Acém 0,5kg', 'category_id': 1, 'brand_id': 1, 'price': 5403},
    {'name': 'Acém 0,5kg', 'category_id': 1, 'brand_id': 51, 'price': 2853},
    {'name': 'Músculo 1kg', 'category_id': 1, 'brand_id': 1, 'price': 1281},
    {'name': 'Músculo 1kg', 'category_id': 1, 'brand_id': 51, 'price': 4180},
    {'name': 'Músculo 0,5kg', 'category_id': 1, 'brand_id': 1, 'price': 2528},
    {'name': 'Músculo 0,5kg', 'category_id': 1, 'brand_id': 51, 'price': 5200},
    {'name': 'Fígado 1kg', 'category_id': 1, 'brand_id': 1, 'price': 2996},
    {'name': 'Fígado 1kg', 'category_id': 1, 'brand_id': 51, 'price': 4958},
    {'name': 'Alcatra 1kg', 'category_id': 1, 'brand_id': 1, 'price': 1888},
    {'name': 'Alcatra 1kg', 'category_id': 1, 'brand_id': 51, 'price': 3053},
    {'name': 'Alcatra 0,5kg', 'category_id': 1, 'brand_id': 1, 'price': 3327},
    {'name': 'Alcatra 0,5kg', 'category_id': 1, 'brand_id': 51, 'price': 5465},
    {'name': 'Fraldinha 1kg', 'category_id': 1, 'brand_id': 1, 'price': 1790},
    {'name': 'Fraldinha 1kg', 'category_id': 1, 'brand_id': 51, 'price': 4035},
    {'name': 'Fraldinha 0,5kg', 'category_id': 1, 'brand_id': 1, 'price': 2370},
    {'name': 'Fraldinha 0,5kg', 'category_id': 1, 'brand_id': 51, 'price': 4521},
    {'name': 'Filé Mignon 1kg', 'category_id': 1, 'brand_id': 1, 'price': 2522},
    {'name': 'Filé Mignon 1kg', 'category_id': 1, 'brand_id': 51, 'price': 5789},
    {'name': 'Filé Mignon 0,5kg', 'category_id': 1, 'brand_id': 1, 'price': 2184},
    {'name': 'Filé Mignon 0,5kg', 'category_id': 1, 'brand_id': 51, 'price': 1708},
    {'name': 'Picanha 1kg', 'category_id': 1, 'brand_id': 1, 'price': 4031},
    {'name': 'Picanha 1kg', 'category_id': 1, 'brand_id': 51, 'price': 3149},
    {'name': 'Picanha 0,5kg', 'category_id': 1, 'brand_id': 1, 'price': 3514},
    {'name': 'Picanha 0,5kg', 'category_id': 1, 'brand_id': 51, 'price': 4669},
    {'name': 'Patinho 1kg', 'category_id': 1, 'brand_id': 1, 'price': 1328},
    {'name': 'Patinho 1kg', 'category_id': 1, 'brand_id': 51, 'price': 4789},
    {'name': 'Patinho 0,5kg', 'category_id': 1, 'brand_id': 1, 'price': 2214},
    {'name': 'Patinho 0,5kg', 'category_id': 1, 'brand_id': 51, 'price': 5696},
    {'name': 'Lagarto 1kg', 'category_id': 1, 'brand_id': 1, 'price': 1557},
    {'name': 'Lagarto 1kg', 'category_id': 1, 'brand_id': 51, 'price': 4909},
    {'name': 'Lagarto 0,5kg', 'category_id': 1, 'brand_id': 1, 'price': 3608},
    {'name': 'Lagarto 0,5kg', 'category_id': 1, 'brand_id': 51, 'price': 3444},
    {'name': 'Contrafilé 1kg', 'category_id': 1, 'brand_id': 1, 'price': 350},
    {'name': 'Contrafilé 1kg', 'category_id': 1, 'brand_id': 51, 'price': 156},
    {'name': 'Contrafilé 0,5kg', 'category_id': 1, 'brand_id': 1, 'price': 1034},
    {'name': 'Contrafilé 0,5kg', 'category_id': 1, 'brand_id': 51, 'price': 2779},
    {'name': 'Maminha 1kg', 'category_id': 1, 'brand_id': 1, 'price': 2903},
    {'name': 'Maminha 1kg', 'category_id': 1, 'brand_id': 51, 'price': 895},
    {'name': 'Maminha 0,5kg', 'category_id': 1, 'brand_id': 1, 'price': 5021},
    {'name': 'Maminha 0,5kg', 'category_id': 1, 'brand_id': 51, 'price': 1236},
    {'name': 'Pernil 1kg', 'category_id': 2, 'brand_id': 1, 'price': 3322},
    {'name': 'Linguiça 1kg', 'category_id': 2, 'brand_id': 1, 'price': 410},
    {'name': 'Filé de Peito 1kg', 'category_id': 3, 'brand_id': 45, 'price': 1577},
    {'name': 'Filé de Peito 1kg', 'category_id': 3, 'brand_id': 46, 'price': 4687},
    {'name': 'Filé de Peito 1kg', 'category_id': 3, 'brand_id': 50, 'price': 2750},
    {'name': 'Coxa e Sobrecoxa 1kg', 'category_id': 3, 'brand_id': 45, 'price': 673},
    {'name': 'Coxa e Sobrecoxa 1kg', 'category_id': 3, 'brand_id': 46, 'price': 2492},
    {'name': 'Coxa e Sobrecoxa 1kg', 'category_id': 3, 'brand_id': 50, 'price': 1257},
    {'name': 'Asa 1kg', 'category_id': 3, 'brand_id': 45, 'price': 1834},
    {'name': 'Asa 1kg', 'category_id': 3, 'brand_id': 46, 'price': 3507},
    {'name': 'Asa 1kg', 'category_id': 3, 'brand_id': 50, 'price': 730},
    {'name': 'Coxinha da Asa 1kg', 'category_id': 3, 'brand_id': 45, 'price': 4482},
    {'name': 'Coxinha da Asa 1kg', 'category_id': 3, 'brand_id': 46, 'price': 4596},
    {'name': 'Coxinha da Asa 1kg', 'category_id': 3, 'brand_id': 50, 'price': 4344},
    {'name': 'Sassami 1kg', 'category_id': 3, 'brand_id': 45, 'price': 4200},
    {'name': 'Sassami 1kg', 'category_id': 3, 'brand_id': 46, 'price': 5001},
    {'name': 'Sassami 1kg', 'category_id': 3, 'brand_id': 50, 'price': 2165},
    {'name': 'Linguiça 1kg', 'category_id': 3, 'brand_id': 45, 'price': 5225},
    {'name': 'Linguiça 1kg', 'category_id': 3, 'brand_id': 46, 'price': 3861},
    {'name': 'Linguiça 1kg', 'category_id': 3, 'brand_id': 50, 'price': 3232},
    {'name': 'Namorado 1kg', 'category_id': 4, 'brand_id': 1, 'price': 1160},
    {'name': 'Tilápia 1kg', 'category_id': 4, 'brand_id': 1, 'price': 4301},
    {'name': 'Salmão 1kg', 'category_id': 4, 'brand_id': 1, 'price': 467},
    {'name': 'Pão Francês 1kg', 'category_id': 6, 'brand_id': 1, 'price': 1674},
    {'name': 'Pão de Cachorro-Quente 1un', 'category_id': 6, 'brand_id': 1, 'price': 2091},
    {'name': 'Pão de Cachorro-Quente 1un', 'category_id': 6, 'brand_id': 1, 'price': 222},
    {'name': 'Pão de Hamburguer 1un', 'category_id': 6, 'brand_id': 1, 'price': 589},
    {'name': 'Pão de Hamburguer 1un', 'category_id': 6, 'brand_id': 1, 'price': 5826},
    {'name': 'Bisnaguinha', 'category_id': 6, 'brand_id': 122, 'price': 104},
    {'name': 'Bisnaguinha', 'category_id': 6, 'brand_id': 123, 'price': 700},
    {'name': 'Bisnaguinha', 'category_id': 6, 'brand_id': 124, 'price': 1793},
    {'name': 'Bisnaguinha', 'category_id': 6, 'brand_id': 125, 'price': 5303},
    {'name': 'Pão de Forma', 'category_id': 6, 'brand_id': 122, 'price': 1354},
    {'name': 'Pão de Forma', 'category_id': 6, 'brand_id': 123, 'price': 676},
    {'name': 'Pão de Forma', 'category_id': 6, 'brand_id': 124, 'price': 3521},
    {'name': 'Pão de Forma', 'category_id': 6, 'brand_id': 125, 'price': 417},
    {'name': 'Queijo Mussarela 100g', 'category_id': 6, 'brand_id': 1, 'price': 2027},
    {'name': 'Queijo Prato 100g', 'category_id': 6, 'brand_id': 1, 'price': 5300},
    {'name': 'Queijo Parmesão 100g', 'category_id': 6, 'brand_id': 1, 'price': 5212},
    {'name': 'Queijo Ralado 100g', 'category_id': 6, 'brand_id': 1, 'price': 2613},
    {'name': 'Queijo Minas 1un', 'category_id': 6, 'brand_id': 1, 'price': 1164},
    {'name': 'Presunto 100g', 'category_id': 6, 'brand_id': 1, 'price': 544},
    {'name': 'Presunto 100g', 'category_id': 6, 'brand_id': 45, 'price': 2811},
    {'name': 'Presunto 100g', 'category_id': 6, 'brand_id': 46, 'price': 853},
    {'name': 'Presunto 100g', 'category_id': 6, 'brand_id': 47, 'price': 3765},
    {'name': 'Presunto 100g', 'category_id': 6, 'brand_id': 50, 'price': 4987},
    {'name': 'Mortadela 100g', 'category_id': 6, 'brand_id': 1, 'price': 3428},
    {'name': 'Mortadela 100g', 'category_id': 6, 'brand_id': 45, 'price': 4608},
    {'name': 'Mortadela 100g', 'category_id': 6, 'brand_id': 46, 'price': 4408},
    {'name': 'Margarina 250g', 'category_id': 6, 'brand_id': 126, 'price': 5747},
    {'name': 'Margarina 500g', 'category_id': 6, 'brand_id': 126, 'price': 5474},
    {'name': 'Margarina 250g', 'category_id': 6, 'brand_id': 127, 'price': 1401},
    {'name': 'Margarina 500g', 'category_id': 6, 'brand_id': 127, 'price': 2678},
    {'name': 'Margarina 250g', 'category_id': 6, 'brand_id': 128, 'price': 1337},
    {'name': 'Margarina 500g', 'category_id': 6, 'brand_id': 128, 'price': 5049},
    {'name': 'Margarina 250g', 'category_id': 6, 'brand_id': 129, 'price': 814},
    {'name': 'Margarina 500g', 'category_id': 6, 'brand_id': 129, 'price': 3515},
    {'name': 'Margarina 250g', 'category_id': 6, 'brand_id': 130, 'price': 4922},
    {'name': 'Margarina 500g', 'category_id': 6, 'brand_id': 130, 'price': 4954},
    {'name': 'Manteiga 200g', 'category_id': 6, 'brand_id': 126, 'price': 3102},
    {'name': 'Requeijão 200g', 'category_id': 6, 'brand_id': 126, 'price': 980},
    {'name': 'Requeijão 200g', 'category_id': 6, 'brand_id': 3, 'price': 1185},
    {'name': 'Requeijão 200g', 'category_id': 6, 'brand_id': 40, 'price': 5950},
    {'name': 'Requeijão 200g', 'category_id': 6, 'brand_id': 39, 'price': 2197},
    {'name': 'Iogurte 1,25kg', 'category_id': 6, 'brand_id': 3, 'price': 5198},
    {'name': 'Iogurte 1,25kg', 'category_id': 6, 'brand_id': 39, 'price': 563},
    {'name': 'Iogurte 1,25kg', 'category_id': 6, 'brand_id': 40, 'price': 294},
    {'name': 'Iogurte 1,25kg', 'category_id': 6, 'brand_id': 41, 'price': 5824},
    {'name': 'Leite 1L', 'category_id': 8, 'brand_id': 10, 'price': 4165},
    {'name': 'Leite 1L', 'category_id': 8, 'brand_id': 11, 'price': 4831},
    {'name': 'Leite 1L', 'category_id': 8, 'brand_id': 29, 'price': 2740},
    {'name': 'Leite 1L', 'category_id': 8, 'brand_id': 42, 'price': 3667},
    {'name': 'Leite Condensado 395g', 'category_id': 6, 'brand_id': 3, 'price': 5394},
    {'name': 'Leite Condensado 395g', 'category_id': 6, 'brand_id': 10, 'price': 5996},
    {'name': 'Leite Condensado 395g', 'category_id': 6, 'brand_id': 42, 'price': 509},
    {'name': 'Creme de Leite 200g', 'category_id': 6, 'brand_id': 3, 'price': 2310},
    {'name': 'Creme de Leite 200g', 'category_id': 6, 'brand_id': 10, 'price': 2747},
    {'name': 'Creme de Leite 200g', 'category_id': 6, 'brand_id': 42, 'price': 4551},
    {'name': 'Achocolatado em Pó 200g', 'category_id': 6, 'brand_id': 28, 'price': 3697},
    {'name': 'Achocolatado 200ml', 'category_id': 8, 'brand_id': 26, 'price': 5096},
    {'name': 'Achocolatado 200ml', 'category_id': 8, 'brand_id': 27, 'price': 1549},
    {'name': 'Achocolatado 200ml', 'category_id': 8, 'brand_id': 28, 'price': 3331},
    {'name': 'Café 500g', 'category_id': 6, 'brand_id': 34, 'price': 3161},
    {'name': 'Café 500g', 'category_id': 6, 'brand_id': 35, 'price': 1185},
    {'name': 'Café 500g', 'category_id': 6, 'brand_id': 36, 'price': 3062},
    {'name': 'Café 500g', 'category_id': 6, 'brand_id': 37, 'price': 2686},
    {'name': 'Café 500g', 'category_id': 6, 'brand_id': 38, 'price': 2002},
    {'name': 'Café 250g', 'category_id': 6, 'brand_id': 34, 'price': 1983},
    {'name': 'Café 250g', 'category_id': 6, 'brand_id': 35, 'price': 3458},
    {'name': 'Café 250g', 'category_id': 6, 'brand_id': 36, 'price': 3912},
    {'name': 'Café 250g', 'category_id': 6, 'brand_id': 37, 'price': 5744},
    {'name': 'Café 250g', 'category_id': 6, 'brand_id': 38, 'price': 245},
    {'name': 'Banana Prata 100g', 'category_id': 5, 'brand_id': 1, 'price': 2549},
    {'name': 'Maçã 100g', 'category_id': 5, 'brand_id': 1, 'price': 2084},
    {'name': 'Uva Vermelha 500g', 'category_id': 5, 'brand_id': 1, 'price': 790},
    {'name': 'Uva Verde 500g', 'category_id': 5, 'brand_id': 1, 'price': 4471},
    {'name': 'Morango 250g', 'category_id': 5, 'brand_id': 1, 'price': 2002},
    {'name': 'Melancia', 'category_id': 5, 'brand_id': 1, 'price': 1469},
    {'name': 'Melão', 'category_id': 5, 'brand_id': 1, 'price': 4222},
    {'name': 'Abacaxi', 'category_id': 5, 'brand_id': 1, 'price': 5909},
    {'name': 'Laranja 100g', 'category_id': 5, 'brand_id': 1, 'price': 628},
    {'name': 'Limão 100g', 'category_id': 5, 'brand_id': 1, 'price': 4847},
    {'name': 'Manga 100g', 'category_id': 5, 'brand_id': 1, 'price': 1213},
    {'name': 'Pera 100g', 'category_id': 5, 'brand_id': 1, 'price': 4450},
    {'name': 'Pêssego 100g', 'category_id': 5, 'brand_id': 1, 'price': 4301},
    {'name': 'Ameixa 100g', 'category_id': 5, 'brand_id': 1, 'price': 1290},
    {'name': 'Kiwi 100g', 'category_id': 5, 'brand_id': 1, 'price': 4221},
    {'name': 'Cenoura 100g', 'category_id': 5, 'brand_id': 1, 'price': 2847},
    {'name': 'Beterraba 100g', 'category_id': 5, 'brand_id': 1, 'price': 3799},
    {'name': 'Batata 100g', 'category_id': 5, 'brand_id': 1, 'price': 4900},
    {'name': 'Batata Doce 100g', 'category_id': 5, 'brand_id': 1, 'price': 4425},
    {'name': 'Batata Inglesa 100g', 'category_id': 5, 'brand_id': 1, 'price': 2189},
    {'name': 'Mandioca 100g', 'category_id': 5, 'brand_id': 1, 'price': 2356},
    {'name': 'Inhame 100g', 'category_id': 5, 'brand_id': 1, 'price': 4233},
    {'name': 'Abóbora', 'category_id': 5, 'brand_id': 1, 'price': 3057},
    {'name': 'Abobrinha', 'category_id': 5, 'brand_id': 1, 'price': 2882},
    {'name': 'Chuchu', 'category_id': 5, 'brand_id': 1, 'price': 3056},
    {'name': 'Pepino 100g', 'category_id': 5, 'brand_id': 1, 'price': 226},
    {'name': 'Tomate 100g', 'category_id': 5, 'brand_id': 1, 'price': 1459},
    {'name': 'Alface', 'category_id': 5, 'brand_id': 1, 'price': 1905},
    {'name': 'Repolho', 'category_id': 5, 'brand_id': 1, 'price': 1297},
    {'name': 'Couve', 'category_id': 5, 'brand_id': 1, 'price': 226},
    {'name': 'Rúcula', 'category_id': 5, 'brand_id': 1, 'price': 1331},
    {'name': 'Agrião', 'category_id': 5, 'brand_id': 1, 'price': 888},
    {'name': 'Espinafre', 'category_id': 5, 'brand_id': 1, 'price': 1619},
    {'name': 'Brócolis', 'category_id': 5, 'brand_id': 1, 'price': 2134},
    {'name': 'Couve-Flor', 'category_id': 5, 'brand_id': 1, 'price': 1522},
    {'name': 'Berinjela', 'category_id': 5, 'brand_id': 1, 'price': 285},
    {'name': 'Pimentão 100g', 'category_id': 5, 'brand_id': 1, 'price': 2915},
    {'name': 'Cebola 100g', 'category_id': 5, 'brand_id': 1, 'price': 1207},
    {'name': 'Alho 100g', 'category_id': 5, 'brand_id': 1, 'price': 1944},
    {'name': 'Gengibre 100g', 'category_id': 5, 'brand_id': 1, 'price': 5490},
    {'name': 'Cebolinha 100g', 'category_id': 5, 'brand_id': 1, 'price': 3112},
    {'name': 'Salsinha 100g', 'category_id': 5, 'brand_id': 1, 'price': 3155},
    {'name': 'Coentro 100g', 'category_id': 5, 'brand_id': 1, 'price': 5007},
    {'name': 'Manjericão 100g', 'category_id': 5, 'brand_id': 1, 'price': 1763},
    {'name': 'Hortelã 100g', 'category_id': 5, 'brand_id': 1, 'price': 3841},
    {'name': 'Alecrim 100g', 'category_id': 5, 'brand_id': 1, 'price': 1140},
    {'name': 'Tomilho 100g', 'category_id': 5, 'brand_id': 1, 'price': 5653},
    {'name': 'Orégano 100g', 'category_id': 5, 'brand_id': 1, 'price': 3200},
    {'name': 'Sálvia 100g', 'category_id': 5, 'brand_id': 1, 'price': 3322},
    {'name': 'Fermento Químico 100g', 'category_id': 5, 'brand_id': 1, 'price': 2042},
    {'name': 'Fermento Biológico 100g', 'category_id': 5, 'brand_id': 1, 'price': 3326},
    {'name': 'Farinha de Trigo 1kg', 'category_id': 7, 'brand_id': 2, 'price': 1112},
    {'name': 'Farinha de Rosca 1kg', 'category_id': 7, 'brand_id': 1, 'price': 442},
    {'name': 'Farinha de Mandioca 1kg', 'category_id': 7, 'brand_id': 1, 'price': 809},
    {'name': 'Arroz Agulha Tipo 1 1kg', 'category_id': 7, 'brand_id': 93, 'price': 416},
    {'name': 'Arroz Agulha Tipo 1 2kg', 'category_id': 7, 'brand_id': 93, 'price': 367},
    {'name': 'Arroz Agulha Tipo 1 5kg', 'category_id': 7, 'brand_id': 93, 'price': 4227},
    {'name': 'Arroz Agulha Tipo 1 1kg', 'category_id': 7, 'brand_id': 69, 'price': 4672},
    {'name': 'Arroz Agulha Tipo 1 2kg', 'category_id': 7, 'brand_id': 69, 'price': 3025},
    {'name': 'Arroz Agulha Tipo 1 5kg', 'category_id': 7, 'brand_id': 69, 'price': 2004},
    {'name': 'Arroz Agulha Tipo 1 1kg', 'category_id': 7, 'brand_id': 70, 'price': 5793},
    {'name': 'Arroz Agulha Tipo 1 2kg', 'category_id': 7, 'brand_id': 70, 'price': 5757},
    {'name': 'Arroz Agulha Tipo 1 5kg', 'category_id': 7, 'brand_id': 70, 'price': 5089},
    {'name': 'Arroz Integral 1kg', 'category_id': 7, 'brand_id': 93, 'price': 4727},
    {'name': 'Arroz Integral 2kg', 'category_id': 7, 'brand_id': 93, 'price': 620},
    {'name': 'Arroz Integral 5kg', 'category_id': 7, 'brand_id': 93, 'price': 5917},
    {'name': 'Arroz Integral 1kg', 'category_id': 7, 'brand_id': 69, 'price': 869},
    {'name': 'Arroz Integral 2kg', 'category_id': 7, 'brand_id': 69, 'price': 126},
    {'name': 'Arroz Integral 5kg', 'category_id': 7, 'brand_id': 69, 'price': 2313},
    {'name': 'Arroz Integral 1kg', 'category_id': 7, 'brand_id': 70, 'price': 5897},
    {'name': 'Arroz Integral 2kg', 'category_id': 7, 'brand_id': 70, 'price': 1168},
    {'name': 'Arroz Integral 5kg', 'category_id': 7, 'brand_id': 70, 'price': 5579},
    {'name': 'Feijão Preto 1kg', 'category_id': 7, 'brand_id': 93, 'price': 205},
    {'name': 'Feijão Preto 1kg', 'category_id': 7, 'brand_id': 70, 'price': 5225},
    {'name': 'Feijão Preto 1kg', 'category_id': 7, 'brand_id': 71, 'price': 2207},
    {'name': 'Feijão Carioca 1kg', 'category_id': 7, 'brand_id': 93, 'price': 2429},
    {'name': 'Feijão Carioca 1kg', 'category_id': 7, 'brand_id': 70, 'price': 3180},
    {'name': 'Feijão Carioca 1kg', 'category_id': 7, 'brand_id': 71, 'price': 4602},
    {'name': 'Refrigerante 350ml', 'category_id': 8, 'brand_id': 12, 'price': 2502},
    {'name': 'Refrigerante 350ml', 'category_id': 8, 'brand_id': 13, 'price': 2560},
    {'name': 'Refrigerante 350ml', 'category_id': 8, 'brand_id': 14, 'price': 3176},
    {'name': 'Refrigerante 350ml', 'category_id': 8, 'brand_id': 15, 'price': 3640},
    {'name': 'Refrigerante de Uva 350ml', 'category_id': 8, 'brand_id': 16, 'price': 5637},
    {'name': 'Refrigerante de Laranja 350ml', 'category_id': 8, 'brand_id': 16, 'price': 1138},
    {'name': 'Refrigerante 350ml', 'category_id': 8, 'brand_id': 17, 'price': 4881},
    {'name': 'Refrigerante 600ml', 'category_id': 8, 'brand_id': 12, 'price': 2599},
    {'name': 'Refrigerante 600ml', 'category_id': 8, 'brand_id': 13, 'price': 2031},
    {'name': 'Refrigerante 600ml', 'category_id': 8, 'brand_id': 14, 'price': 660},
    {'name': 'Refrigerante 600ml', 'category_id': 8, 'brand_id': 15, 'price': 3816},
    {'name': 'Refrigerante de Uva 600ml', 'category_id': 8, 'brand_id': 16, 'price': 1621},
    {'name': 'Refrigerante de Laranja 600ml', 'category_id': 8, 'brand_id': 16, 'price': 5894},
    {'name': 'Refrigerante 600ml', 'category_id': 8, 'brand_id': 17, 'price': 5666},
    {'name': 'Refrigerante 1L', 'category_id': 8, 'brand_id': 12, 'price': 892},
    {'name': 'Refrigerante 1L', 'category_id': 8, 'brand_id': 13, 'price': 1109},
    {'name': 'Refrigerante 1L', 'category_id': 8, 'brand_id': 14, 'price': 4064},
    {'name': 'Refrigerante 1L', 'category_id': 8, 'brand_id': 15, 'price': 3941},
    {'name': 'Refrigerante de Uva 1L', 'category_id': 8, 'brand_id': 16, 'price': 5664},
    {'name': 'Refrigerante de Laranja 1L', 'category_id': 8, 'brand_id': 16, 'price': 5987},
    {'name': 'Refrigerante 1L', 'category_id': 8, 'brand_id': 17, 'price': 2384},
    {'name': 'Refrigerante 1,5L', 'category_id': 8, 'brand_id': 12, 'price': 475},
    {'name': 'Refrigerante 1,5L', 'category_id': 8, 'brand_id': 13, 'price': 4475},
    {'name': 'Refrigerante 1,5L', 'category_id': 8, 'brand_id': 14, 'price': 4693},
    {'name': 'Refrigerante 1,5L', 'category_id': 8, 'brand_id': 15, 'price': 996},
    {'name': 'Refrigerante de Uva 1,5L', 'category_id': 8, 'brand_id': 16, 'price': 3620},
    {'name': 'Refrigerante de Laranja 1,5L', 'category_id': 8, 'brand_id': 16, 'price': 3379},
    {'name': 'Refrigerante 1,5L', 'category_id': 8, 'brand_id': 17, 'price': 5628},
    {'name': 'Refrigerante 2L', 'category_id': 8, 'brand_id': 12, 'price': 2957},
    {'name': 'Refrigerante 2L', 'category_id': 8, 'brand_id': 13, 'price': 2059},
    {'name': 'Refrigerante 2L', 'category_id': 8, 'brand_id': 14, 'price': 5383},
    {'name': 'Refrigerante 2L', 'category_id': 8, 'brand_id': 15, 'price': 5159},
    {'name': 'Refrigerante de Uva 2L', 'category_id': 8, 'brand_id': 16, 'price': 1142},
    {'name': 'Refrigerante de Laranja 2L', 'category_id': 8, 'brand_id': 16, 'price': 5526},
    {'name': 'Refrigerante 2L', 'category_id': 8, 'brand_id': 17, 'price': 993},
    {'name': 'Refrigerante 2,5L', 'category_id': 8, 'brand_id': 12, 'price': 629},
    {'name': 'Refrigerante 2,5L', 'category_id': 8, 'brand_id': 13, 'price': 1858},
    {'name': 'Refrigerante 2,5L', 'category_id': 8, 'brand_id': 14, 'price': 5085},
    {'name': 'Refrigerante 2,5L', 'category_id': 8, 'brand_id': 15, 'price': 3408},
    {'name': 'Refrigerante de Uva 2,5L', 'category_id': 8, 'brand_id': 16, 'price': 1884},
    {'name': 'Refrigerante de Laranja 2,5L', 'category_id': 8, 'brand_id': 16, 'price': 5472},
    {'name': 'Refrigerante 2,5L', 'category_id': 8, 'brand_id': 17, 'price': 2216},
    {'name': 'Refrigerante 3L', 'category_id': 8, 'brand_id': 12, 'price': 1098},
    {'name': 'Refrigerante 3L', 'category_id': 8, 'brand_id': 13, 'price': 3006},
    {'name': 'Refrigerante 3L', 'category_id': 8, 'brand_id': 14, 'price': 1312},
    {'name': 'Refrigerante 3L', 'category_id': 8, 'brand_id': 15, 'price': 510},
    {'name': 'Refrigerante de Uva 3L', 'category_id': 8, 'brand_id': 16, 'price': 3001},
    {'name': 'Refrigerante de Laranja 3L', 'category_id': 8, 'brand_id': 16, 'price': 2843},
    {'name': 'Refrigerante 3L', 'category_id': 8, 'brand_id': 17, 'price': 2440},
    {'name': 'Suco de Uva 1L', 'category_id': 8, 'brand_id': 23, 'price': 5284},
    {'name': 'Suco de Uva 1L', 'category_id': 8, 'brand_id': 24, 'price': 5543},
    {'name': 'Suco de Uva 1L', 'category_id': 8, 'brand_id': 25, 'price': 754},
    {'name': 'Suco de Laranja 1L', 'category_id': 8, 'brand_id': 23, 'price': 5193},
    {'name': 'Suco de Laranja 1L', 'category_id': 8, 'brand_id': 24, 'price': 2424},
    {'name': 'Suco de Laranja 1L', 'category_id': 8, 'brand_id': 25, 'price': 5975},
    {'name': 'Suco de Pêssego 1L', 'category_id': 8, 'brand_id': 23, 'price': 949},
    {'name': 'Suco de Pêssego 1L', 'category_id': 8, 'brand_id': 24, 'price': 5213},
    {'name': 'Suco de Pêssego 1L', 'category_id': 8, 'brand_id': 25, 'price': 3307},
    {'name': 'Suco de Manga 1L', 'category_id': 8, 'brand_id': 23, 'price': 2689},
    {'name': 'Suco de Manga 1L', 'category_id': 8, 'brand_id': 24, 'price': 2763},
    {'name': 'Suco de Manga 1L', 'category_id': 8, 'brand_id': 25, 'price': 5279},
    {'name': 'Suco de Maçã 1L', 'category_id': 8, 'brand_id': 23, 'price': 5549},
    {'name': 'Suco de Maçã 1L', 'category_id': 8, 'brand_id': 24, 'price': 816},
    {'name': 'Suco de Maçã 1L', 'category_id': 8, 'brand_id': 25, 'price': 3263},
    {'name': 'Água Mineral 500ml', 'category_id': 8, 'brand_id': 18, 'price': 5091},
    {'name': 'Água Mineral 500ml', 'category_id': 8, 'brand_id': 19, 'price': 5106},
    {'name': 'Água Mineral 500ml', 'category_id': 8, 'brand_id': 20, 'price': 3203},
    {'name': 'Água Mineral 500ml', 'category_id': 8, 'brand_id': 21, 'price': 4111},
    {'name': 'Água Mineral 1,5L', 'category_id': 8, 'brand_id': 18, 'price': 1938},
    {'name': 'Água Mineral 1,5L', 'category_id': 8, 'brand_id': 19, 'price': 5707},
    {'name': 'Água Mineral 1,5L', 'category_id': 8, 'brand_id': 20, 'price': 1544},
    {'name': 'Água Mineral 1,5L', 'category_id': 8, 'brand_id': 21, 'price': 4870},
    {'name': 'Chá', 'category_id': 8, 'brand_id': 22, 'price': 5552},
    {'name': 'Cerveja 350ml', 'category_id': 8, 'brand_id': 57, 'price': 1244},
    {'name': 'Cerveja 350ml', 'category_id': 8, 'brand_id': 58, 'price': 3805},
    {'name': 'Cerveja 350ml', 'category_id': 8, 'brand_id': 59, 'price': 2057},
    {'name': 'Cerveja 350ml', 'category_id': 8, 'brand_id': 60, 'price': 5012},
    {'name': 'Cerveja 350ml', 'category_id': 8, 'brand_id': 61, 'price': 1609},
    {'name': 'Cerveja 350ml', 'category_id': 8, 'brand_id': 62, 'price': 2991},
    {'name': 'Energético 250ml', 'category_id': 8, 'brand_id': 63, 'price': 2085},
    {'name': 'Energético 473ml', 'category_id': 8, 'brand_id': 64, 'price': 1545},
    {'name': 'Detergente 500ml', 'category_id': 9, 'brand_id': 115, 'price': 1092},
    {'name': 'Detergente 500ml', 'category_id': 9, 'brand_id': 117, 'price': 4841},
    {'name': 'Sabonete', 'category_id': 9, 'brand_id': 75, 'price': 3914},
    {'name': 'Sabonete', 'category_id': 9, 'brand_id': 76, 'price': 235},
    {'name': 'Sabonete', 'category_id': 9, 'brand_id': 77, 'price': 127},
    {'name': 'Sabonete', 'category_id': 9, 'brand_id': 78, 'price': 4437},
    {'name': 'Sabonete', 'category_id': 9, 'brand_id': 116, 'price': 4377},
    {'name': 'Shampoo', 'category_id': 9, 'brand_id': 79, 'price': 4147},
    {'name': 'Shampoo', 'category_id': 9, 'brand_id': 80, 'price': 1101},
    {'name': 'Shampoo', 'category_id': 9, 'brand_id': 81, 'price': 4865},
    {'name': 'Shampoo', 'category_id': 9, 'brand_id': 82, 'price': 4021},
    {'name': 'Shampoo', 'category_id': 9, 'brand_id': 83, 'price': 5241},
    {'name': 'Condicionador', 'category_id': 9, 'brand_id': 79, 'price': 4422},
    {'name': 'Condicionador', 'category_id': 9, 'brand_id': 80, 'price': 2645},
    {'name': 'Condicionador', 'category_id': 9, 'brand_id': 81, 'price': 1898},
    {'name': 'Condicionador', 'category_id': 9, 'brand_id': 82, 'price': 2137},
    {'name': 'Condicionador', 'category_id': 9, 'brand_id': 83, 'price': 1403},
    {'name': 'Papel Higiênico 4un', 'category_id': 9, 'brand_id': 85, 'price': 5017},
    {'name': 'Papel Higiênico 4un', 'category_id': 9, 'brand_id': 86, 'price': 4718},
    {'name': 'Papel Higiênico 4un', 'category_id': 9, 'brand_id': 87, 'price': 5025},
    {'name': 'Papel Higiênico 12un', 'category_id': 9, 'brand_id': 85, 'price': 4625},
    {'name': 'Papel Higiênico 12un', 'category_id': 9, 'brand_id': 86, 'price': 333},
    {'name': 'Papel Higiênico 12un', 'category_id': 9, 'brand_id': 87, 'price': 5097},
    {'name': 'Papel Higiênico 24un', 'category_id': 9, 'brand_id': 85, 'price': 669},
    {'name': 'Papel Higiênico 24un', 'category_id': 9, 'brand_id': 86, 'price': 2383},
    {'name': 'Papel Higiênico 24un', 'category_id': 9, 'brand_id': 87, 'price': 4442},
    {'name': 'Pasta de Dente 90g', 'category_id': 9, 'brand_id': 132, 'price': 2252},
    {'name': 'Pasta de Dente 90g', 'category_id': 9, 'brand_id': 133, 'price': 2610},
    {'name': 'Pasta de Dente 90g', 'category_id': 9, 'brand_id': 134, 'price': 488},
    {'name': 'Amaciante 2L', 'category_id': 9, 'brand_id': 108, 'price': 3473},
    {'name': 'Amaciante 2L', 'category_id': 9, 'brand_id': 109, 'price': 1070},
    {'name': 'Amaciante 2L', 'category_id': 9, 'brand_id': 110, 'price': 3814},
    {'name': 'Amaciante 2L', 'category_id': 9, 'brand_id': 111, 'price': 5169},
    {'name': 'Amaciante 2L', 'category_id': 9, 'brand_id': 112, 'price': 4097},
    {'name': 'Amaciante 2L', 'category_id': 9, 'brand_id': 113, 'price': 2618},
    {'name': 'Amaciante 2L', 'category_id': 9, 'brand_id': 114, 'price': 5873},
    {'name': 'Sabão em Pó 2,2kg', 'category_id': 9, 'brand_id': 110, 'price': 1809},
    {'name': 'Sabão em Pó 2,2kg', 'category_id': 9, 'brand_id': 112, 'price': 4593},
    {'name': 'Sabão Líquido 3L', 'category_id': 9, 'brand_id': 110, 'price': 1063},
    {'name': 'Sabão Líquido 3L', 'category_id': 9, 'brand_id': 112, 'price': 4051},
    {'name': 'Desinfetante 2L', 'category_id': 9, 'brand_id': 115, 'price': 4655},
    {'name': 'Água Sanitária 1L', 'category_id': 9, 'brand_id': 1, 'price': 3228},
    {'name': 'Água Sanitária 2L', 'category_id': 9, 'brand_id': 1, 'price': 169},
    {'name': 'Água Sanitária 5L', 'category_id': 9, 'brand_id': 1, 'price': 955},
    {'name': 'Lustra Móveis 200ml', 'category_id': 9, 'brand_id': 1, 'price': 1498},
    {'name': 'Limpa Vidros 500ml', 'category_id': 9, 'brand_id': 1, 'price': 4806},
    {'name': 'Esponja de Aço 8un', 'category_id': 9, 'brand_id': 118, 'price': 1387},
    {'name': 'Desengordurante 500ml', 'category_id': 9, 'brand_id': 1, 'price': 110},
    {'name': 'Fio Dental 50m', 'category_id': 9, 'brand_id': 1, 'price': 4336},
    {'name': 'Pizza Bolonhesa 460g', 'category_id': 10, 'brand_id': 45, 'price': 2523},
    {'name': 'Pizza Bolonhesa 460g', 'category_id': 10, 'brand_id': 46, 'price': 3605},
    {'name': 'Pizza Bolonhesa 460g', 'category_id': 10, 'brand_id': 47, 'price': 455},
    {'name': 'Pizza Bolonhesa 460g', 'category_id': 10, 'brand_id': 49, 'price': 5070},
    {'name': 'Pizza Bolonhesa 460g', 'category_id': 10, 'brand_id': 50, 'price': 472},
    {'name': 'Pizza de Frango 460g', 'category_id': 10, 'brand_id': 45, 'price': 3366},
    {'name': 'Pizza de Frango 460g', 'category_id': 10, 'brand_id': 46, 'price': 5154},
    {'name': 'Pizza de Frango 460g', 'category_id': 10, 'brand_id': 47, 'price': 3531},
    {'name': 'Pizza de Frango 460g', 'category_id': 10, 'brand_id': 49, 'price': 897},
    {'name': 'Pizza de Frango 460g', 'category_id': 10, 'brand_id': 50, 'price': 203},
    {'name': 'Pizza 4 Queijos 460g', 'category_id': 10, 'brand_id': 45, 'price': 2796},
    {'name': 'Pizza 4 Queijos 460g', 'category_id': 10, 'brand_id': 46, 'price': 2924},
    {'name': 'Pizza 4 Queijos 460g', 'category_id': 10, 'brand_id': 47, 'price': 1632},
    {'name': 'Pizza 4 Queijos 460g', 'category_id': 10, 'brand_id': 49, 'price': 4465},
    {'name': 'Pizza 4 Queijos 460g', 'category_id': 10, 'brand_id': 50, 'price': 2933},
    {'name': 'Pizza Calabresa 460g', 'category_id': 10, 'brand_id': 45, 'price': 947},
    {'name': 'Pizza Calabresa 460g', 'category_id': 10, 'brand_id': 46, 'price': 2032},
    {'name': 'Pizza Calabresa 460g', 'category_id': 10, 'brand_id': 47, 'price': 3612},
    {'name': 'Pizza Calabresa 460g', 'category_id': 10, 'brand_id': 49, 'price': 2210},
    {'name': 'Pizza Calabresa 460g', 'category_id': 10, 'brand_id': 50, 'price': 5182},
    {'name': 'Lasanha Bolonhesa 600g', 'category_id': 10, 'brand_id': 45, 'price': 5405},
    {'name': 'Lasanha Bolonhesa 600g', 'category_id': 10, 'brand_id': 46, 'price': 204},
    {'name': 'Lasanha Bolonhesa 600g', 'category_id': 10, 'brand_id': 47, 'price': 128},
    {'name': 'Lasanha Bolonhesa 600g', 'category_id': 10, 'brand_id': 49, 'price': 3974},
    {'name': 'Lasanha Bolonhesa 600g', 'category_id': 10, 'brand_id': 50, 'price': 2804},
    {'name': 'Lasanha de Frango 600g', 'category_id': 10, 'brand_id': 45, 'price': 4001},
    {'name': 'Lasanha de Frango 600g', 'category_id': 10, 'brand_id': 46, 'price': 5654},
    {'name': 'Lasanha de Frango 600g', 'category_id': 10, 'brand_id': 47, 'price': 1644},
    {'name': 'Lasanha de Frango 600g', 'category_id': 10, 'brand_id': 49, 'price': 5029},
    {'name': 'Lasanha de Frango 600g', 'category_id': 10, 'brand_id': 50, 'price': 3797},
    {'name': 'Lasanha 4 Queijos 600g', 'category_id': 10, 'brand_id': 45, 'price': 3350},
    {'name': 'Lasanha 4 Queijos 600g', 'category_id': 10, 'brand_id': 46, 'price': 4710},
    {'name': 'Lasanha 4 Queijos 600g', 'category_id': 10, 'brand_id': 47, 'price': 1769},
    {'name': 'Lasanha 4 Queijos 600g', 'category_id': 10, 'brand_id': 49, 'price': 1325},
    {'name': 'Lasanha 4 Queijos 600g', 'category_id': 10, 'brand_id': 50, 'price': 3654},
    {'name': 'Lasanha Calabresa 600g', 'category_id': 10, 'brand_id': 45, 'price': 5585},
    {'name': 'Lasanha Calabresa 600g', 'category_id': 10, 'brand_id': 46, 'price': 1227},
    {'name': 'Lasanha Calabresa 600g', 'category_id': 10, 'brand_id': 47, 'price': 1397},
    {'name': 'Lasanha Calabresa 600g', 'category_id': 10, 'brand_id': 49, 'price': 2633},
    {'name': 'Lasanha Calabresa 600g', 'category_id': 10, 'brand_id': 50, 'price': 3592},
    {'name': 'Hamburguer de Carne 12 unidades', 'category_id': 10, 'brand_id': 45, 'price': 5819},
    {'name': 'Hamburguer de Carne 12 unidades', 'category_id': 10, 'brand_id': 46, 'price': 4385},
    {'name': 'Hamburguer de Carne 12 unidades', 'category_id': 10, 'brand_id': 47, 'price': 3947},
    {'name': 'Hamburguer de Carne 12 unidades', 'category_id': 10, 'brand_id': 48, 'price': 3613},
    {'name': 'Hamburguer de Carne 12 unidades', 'category_id': 10, 'brand_id': 49, 'price': 2549},
    {'name': 'Hamburguer de Carne 12 unidades', 'category_id': 10, 'brand_id': 50, 'price': 859},
    {'name': 'Hamburguer de Carne 12 unidades', 'category_id': 10, 'brand_id': 51, 'price': 4620},
    {'name': 'Hamburguer de Frango 12 unidades', 'category_id': 10, 'brand_id': 45, 'price': 571},
    {'name': 'Hamburguer de Frango 12 unidades', 'category_id': 10, 'brand_id': 46, 'price': 3604},
    {'name': 'Hamburguer de Frango 12 unidades', 'category_id': 10, 'brand_id': 47, 'price': 1555},
    {'name': 'Hamburguer de Frango 12 unidades', 'category_id': 10, 'brand_id': 48, 'price': 2906},
    {'name': 'Hamburguer de Frango 12 unidades', 'category_id': 10, 'brand_id': 49, 'price': 2541},
    {'name': 'Hamburguer de Frango 12 unidades', 'category_id': 10, 'brand_id': 50, 'price': 1007},
    {'name': 'Hamburguer de Frango 12 unidades', 'category_id': 10, 'brand_id': 51, 'price': 233},
    {'name': 'Hamburguer Misto 12 unidades', 'category_id': 10, 'brand_id': 45, 'price': 1777},
    {'name': 'Hamburguer Misto 12 unidades', 'category_id': 10, 'brand_id': 46, 'price': 3430},
    {'name': 'Hamburguer Misto 12 unidades', 'category_id': 10, 'brand_id': 47, 'price': 2933},
    {'name': 'Hamburguer Misto 12 unidades', 'category_id': 10, 'brand_id': 48, 'price': 4800},
    {'name': 'Hamburguer Misto 12 unidades', 'category_id': 10, 'brand_id': 49, 'price': 1886},
    {'name': 'Hamburguer Misto 12 unidades', 'category_id': 10, 'brand_id': 50, 'price': 539},
    {'name': 'Hamburguer Misto 12 unidades', 'category_id': 10, 'brand_id': 51, 'price': 1149},
    {'name': 'Chocolate ao Leite 90g', 'category_id': 11, 'brand_id': 52, 'price': 887},
    {'name': 'Chocolate ao Leite 90g', 'category_id': 11, 'brand_id': 53, 'price': 5563},
    {'name': 'Chocolate ao Leite 90g', 'category_id': 11, 'brand_id': 54, 'price': 454},
    {'name': 'Chocolate ao Leite 90g', 'category_id': 11, 'brand_id': 55, 'price': 5205},
    {'name': 'Chocolate ao Leite 90g', 'category_id': 11, 'brand_id': 56, 'price': 4327},
    {'name': 'Chocolate Branco 90g', 'category_id': 11, 'brand_id': 52, 'price': 1238},
    {'name': 'Chocolate Branco 90g', 'category_id': 11, 'brand_id': 53, 'price': 974},
    {'name': 'Chocolate Branco 90g', 'category_id': 11, 'brand_id': 54, 'price': 5160},
    {'name': 'Chocolate Branco 90g', 'category_id': 11, 'brand_id': 55, 'price': 2124},
    {'name': 'Chocolate Branco 90g', 'category_id': 11, 'brand_id': 56, 'price': 1673},
    {'name': 'Ração para Cães 1kg', 'category_id': 12, 'brand_id': 88, 'price': 1798},
    {'name': 'Ração para Cães 1kg', 'category_id': 12, 'brand_id': 89, 'price': 916},
    {'name': 'Ração para Cães 1kg', 'category_id': 12, 'brand_id': 90, 'price': 3892},
    {'name': 'Ração para Cães 1kg', 'category_id': 12, 'brand_id': 91, 'price': 2383},
    {'name': 'Ração para Gatos 1kg', 'category_id': 12, 'brand_id': 88, 'price': 5764},
    {'name': 'Ração para Gatos 1kg', 'category_id': 12, 'brand_id': 92, 'price': 1479},
    {'name': 'Ração para Cães 5kg', 'category_id': 12, 'brand_id': 88, 'price': 1293},
    {'name': 'Ração para Cães 5kg', 'category_id': 12, 'brand_id': 89, 'price': 484},
    {'name': 'Ração para Cães 5kg', 'category_id': 12, 'brand_id': 90, 'price': 1750},
    {'name': 'Ração para Cães 5kg', 'category_id': 12, 'brand_id': 91, 'price': 2980},
    {'name': 'Ração para Gatos 5kg', 'category_id': 12, 'brand_id': 88, 'price': 4060},
    {'name': 'Ração para Gatos 5kg', 'category_id': 12, 'brand_id': 92, 'price': 1991},
    {'name': 'Ração para Cães 10kg', 'category_id': 12, 'brand_id': 88, 'price': 568},
    {'name': 'Ração para Cães 10kg', 'category_id': 12, 'brand_id': 89, 'price': 641},
    {'name': 'Ração para Cães 10kg', 'category_id': 12, 'brand_id': 90, 'price': 1606},
    {'name': 'Ração para Cães 10kg', 'category_id': 12, 'brand_id': 91, 'price': 2984},
    {'name': 'Ração para Gatos 10kg', 'category_id': 12, 'brand_id': 88, 'price': 3729},
    {'name': 'Ração para Gatos 10kg', 'category_id': 12, 'brand_id': 92, 'price': 4120},
    {'name': 'Ração para Cães 15kg', 'category_id': 12, 'brand_id': 88, 'price': 3675},
    {'name': 'Ração para Cães 15kg', 'category_id': 12, 'brand_id': 89, 'price': 1332},
    {'name': 'Ração para Cães 15kg', 'category_id': 12, 'brand_id': 90, 'price': 4321},
    {'name': 'Ração para Cães 15kg', 'category_id': 12, 'brand_id': 91, 'price': 1864},
    {'name': 'Ração para Gatos 15kg', 'category_id': 12, 'brand_id': 88, 'price': 3194},
    {'name': 'Ração para Gatos 15kg', 'category_id': 12, 'brand_id': 92, 'price': 3897},
    {'name': 'Biscoito Recheado', 'category_id': 13, 'brand_id': 2, 'price': 4195},
    {'name': 'Biscoito Recheado', 'category_id': 13, 'brand_id': 3, 'price': 2453},
    {'name': 'Biscoito Recheado', 'category_id': 13, 'brand_id': 4, 'price': 454},
    {'name': 'Biscoito Recheado', 'category_id': 13, 'brand_id': 5, 'price': 2095},
    {'name': 'Biscoito Recheado', 'category_id': 13, 'brand_id': 6, 'price': 591},
    {'name': 'Biscoito Recheado', 'category_id': 13, 'brand_id': 7, 'price': 5014},
    {'name': 'Biscoito Recheado', 'category_id': 13, 'brand_id': 8, 'price': 5935},
    {'name': 'Biscoito Recheado', 'category_id': 13, 'brand_id': 9, 'price': 924},
    {'name': 'Biscoito Salgado', 'category_id': 13, 'brand_id': 3, 'price': 3022},
    {'name': 'Biscoito Salgado', 'category_id': 13, 'brand_id': 5, 'price': 1538},
    {'name': 'Biscoito Salgado', 'category_id': 13, 'brand_id': 6, 'price': 2781},
    {'name': 'Biscoito Salgado', 'category_id': 13, 'brand_id': 7, 'price': 2565},
    {'name': 'Biscoito Salgado', 'category_id': 13, 'brand_id': 8, 'price': 1393}
]
# Generating real brands
def generate_brands():
    brands = []
    for brand_name in real_brands:
        brand = schemas.BrandCreate(name=brand_name)
        db_brand = crud.create_brand(db=db, brand=brand)
        brands.append(db_brand)
    return brands

# Generating categories
def generate_categories():
    categories_created = []
    for category_name in categories:
        category = schemas.CategoryCreate(name=category_name)
        db_category = crud.create_category(db=db, category=category)
        categories_created.append(db_category)
    return categories_created

# Generating supermarkets
def generate_supermarkets():
    supermarkets_created = []
    for supermarket in supermarkets:
        supermarket = schemas.SupermarketCreate(
            name=supermarket["name"],
            address=supermarket["address"]
        )
        db_supermarket = crud.create_supermarket(db=db, supermarket=supermarket)
        supermarkets_created.append(db_supermarket)
    return supermarkets_created

# Generating products associated with real brands and categories
def generate_products():
    products_created = []
    for product in products:
        product_create = schemas.ProductCreate(
            name=product["name"],
            category_id=product["category_id"],
            brand_id=product["brand_id"],
            price=product["price"]
        )
        db_product = crud.create_product(db=db, product=product_create)
        products_created.append(db_product)
    return products_created

# Associating products with supermarkets
def associate_products_with_supermarkets():
    # Fetch all products and supermarkets from the database
    db_products = db.query(models.product.Product).all()
    db_supermarkets = db.query(models.supermarket.Supermarket).all()

    # Iterate over each product and associate it with multiple supermarkets
    for product in db_products:
        # Randomly select supermarkets to associate with each product
        num_supermarkets = random.randint(1, len(db_supermarkets))
        selected_supermarkets = random.sample(db_supermarkets, num_supermarkets)

        # Associate product with selected supermarkets
        for supermarket in selected_supermarkets:
            product.supermarkets.append(supermarket)

    # Commit the changes to the database
    db.commit()

# Executing the functions to create and associate data
try:
    generate_categories()
    generate_brands()
    generate_supermarkets()
    generate_products()
    associate_products_with_supermarkets()
    print("Banco de dados populado com sucesso!")
except Exception as e:
    print(f"Erro ao popular banco de dados: {e}")
finally:
    db.close()