products = [
  {"name": "Acém 1kg", "category_id": [2], "brand_id": 1},
  {"name": "Acém 1kg", "category_id": [2], "brand_id": 51},
  {"name": "Acém 0,5kg", "category_id": [2], "brand_id": 1},
  {"name": "Acém 0,5kg", "category_id": [2], "brand_id": 51},
  {"name": "Músculo 1kg", "category_id": [2], "brand_id": 1},
  {"name": "Músculo 1kg", "category_id": [2], "brand_id": 51},
  {"name": "Músculo 0,5kg", "category_id": [2], "brand_id": 1},
  {"name": "Músculo 0,5kg", "category_id": [2], "brand_id": 51},
  {"name": "Fígado 1kg", "category_id": [2], "brand_id": 1},
  {"name": "Fígado 1kg", "category_id": [2], "brand_id": 51},
  {"name": "Alcatra 1kg", "category_id": [2], "brand_id": 1},
  {"name": "Alcatra 1kg", "category_id": [2], "brand_id": 51},
  {"name": "Alcatra 0,5kg", "category_id": [2], "brand_id": 1},
  {"name": "Alcatra 0,5kg", "category_id": [2], "brand_id": 51},
  {"name": "Fraldinha 1kg", "category_id": [2], "brand_id": 1},
  {"name": "Fraldinha 1kg", "category_id": [2], "brand_id": 51},
  {"name": "Fraldinha 0,5kg", "category_id": [2], "brand_id": 1},
  {"name": "Fraldinha 0,5kg", "category_id": [2], "brand_id": 51},
  {"name": "Filé Mignon 1kg", "category_id": [2], "brand_id": 1},
  {"name": "Filé Mignon 1kg", "category_id": [2], "brand_id": 51},
  {"name": "Filé Mignon 0,5kg", "category_id": [2], "brand_id": 1},
  {"name": "Filé Mignon 0,5kg", "category_id": [2], "brand_id": 51},
  {"name": "Picanha 1kg", "category_id": [2], "brand_id": 1},
  {"name": "Picanha 1kg", "category_id": [2], "brand_id": 51},
  {"name": "Picanha 0,5kg", "category_id": [2], "brand_id": 1},
  {"name": "Picanha 0,5kg", "category_id": [2], "brand_id": 51},
  {"name": "Patinho 1kg", "category_id": [2], "brand_id": 1},
  {"name": "Patinho 1kg", "category_id": [2], "brand_id": 51},
  {"name": "Patinho 0,5kg", "category_id": [2], "brand_id": 1},
  {"name": "Patinho 0,5kg", "category_id": [2], "brand_id": 51},
  {"name": "Lagarto 1kg", "category_id": [2], "brand_id": 1},
  {"name": "Lagarto 1kg", "category_id": [2], "brand_id": 51},
  {"name": "Lagarto 0,5kg", "category_id": [2], "brand_id": 1},
  {"name": "Lagarto 0,5kg", "category_id": [2], "brand_id": 51},
  {"name": "Contrafilé 1kg", "category_id": [2], "brand_id": 1},
  {"name": "Contrafilé 1kg", "category_id": [2], "brand_id": 51},
  {"name": "Contrafilé 0,5kg", "category_id": [2], "brand_id": 1},
  {"name": "Contrafilé 0,5kg", "category_id": [2], "brand_id": 51},
  {"name": "Maminha 1kg", "category_id": [2], "brand_id": 1},
  {"name": "Maminha 1kg", "category_id": [2], "brand_id": 51},
  {"name": "Maminha 0,5kg", "category_id": [2], "brand_id": 1},
  {"name": "Maminha 0,5kg", "category_id": [2], "brand_id": 51}
  {"name": "Pernil 1kg", "category_id": [3], "brand_id": 1},
  {"name": "Linguiça 1kg", "category_id": [3], "brand_id": 1},
  {"name": "Filé de Peito 1kg", "category_id": [4], "brand_id": 45},
  {"name": "Filé de Peito 1kg", "category_id": [4], "brand_id": 46},
  {"name": "Filé de Peito 1kg", "category_id": [4], "brand_id": 50},
  {"name": "Coxa e Sobrecoxa 1kg", "category_id": [4], "brand_id": 45},
  {"name": "Coxa e Sobrecoxa 1kg", "category_id": [4], "brand_id": 46},
  {"name": "Coxa e Sobrecoxa 1kg", "category_id": [4], "brand_id": 50},
  {"name": "Asa 1kg", "category_id": [4], "brand_id": 45},
  {"name": "Asa 1kg", "category_id": [4], "brand_id": 46},
  {"name": "Asa 1kg", "category_id": [4], "brand_id": 50},
  {"name": "Coxinha da Asa 1kg", "category_id": [4], "brand_id": 45},
  {"name": "Coxinha da Asa 1kg", "category_id": [4], "brand_id": 46},
  {"name": "Coxinha da Asa 1kg", "category_id": [4], "brand_id": 50},
  {"name": "Sassami 1kg", "category_id": [4], "brand_id": 45},
  {"name": "Sassami 1kg", "category_id": [4], "brand_id": 46},
  {"name": "Sassami 1kg", "category_id": [4], "brand_id": 50},
  {"name": "Linguiça 1kg", "category_id": [4], "brand_id": 45},
  {"name": "Linguiça 1kg", "category_id": [4], "brand_id": 46},
  {"name": "Linguiça 1kg", "category_id": [4], "brand_id": 50},
  {"name": "Namorado 1kg", "category_id": [5], "brand_id": 1},
  {"name": "Tilápia 1kg", "category_id": [5], "brand_id": 1},
  {"name": "Salmão 1kg", "category_id": [5], "brand_id": 1},
  {"name": "Pão Francês 1kg", "category_id": [7], "brand_id": 1},
  {"name": "Pão de Cachorro-Quente 1un", "category_id": [7], "brand_id": 1},
  {"name": "Pão de Cachorro-Quente 1un", "category_id": [7], "brand_id": 1},
  {"name": "Pão de Hamburguer 1un", "category_id": [7], "brand_id": 1},
  {"name": "Pão de Hamburguer 1un", "category_id": [7], "brand_id": 1},
  {"name": "Bisnaguinha", "category_id": [7], "brand_id": 122},
  {"name": "Bisnaguinha", "category_id": [7], "brand_id": 123},
  {"name": "Bisnaguinha", "category_id": [7], "brand_id": 124},
  {"name": "Bisnaguinha", "category_id": [7], "brand_id": 125},
  {"name": "Pão de Forma", "category_id": [7], "brand_id": 122},
  {"name": "Pão de Forma", "category_id": [7], "brand_id": 123},
  {"name": "Pão de Forma", "category_id": [7], "brand_id": 124},
  {"name": "Pão de Forma", "category_id": [7], "brand_id": 125},
  {"name": "Queijo Mussarela 100g", "category_id": [11, 7], "brand_id": 1},
  {"name": "Queijo Prato 100g", "category_id": [11, 7], "brand_id": 1},
  {"name": "Queijo Parmesão 100g", "category_id": [11, 7], "brand_id": 1},
  {"name": "Queijo Ralado 100g", "category_id": [11, 7], "brand_id": 1},
  {"name": "Queijo Minas 1un", "category_id": [11, 7], "brand_id": 1},
  {"name": "Presunto 100g", "category_id": [1, 7], "brand_id": 1},
  {"name": "Presunto 100g", "category_id": [1, 7], "brand_id": 45},
  {"name": "Presunto 100g", "category_id": [1, 7], "brand_id": 46},
  {"name": "Presunto 100g", "category_id": [1, 7], "brand_id": 47},
  {"name": "Presunto 100g", "category_id": [1, 7], "brand_id": 50},
  {"name": "Mortadela 100g", "category_id": [1, 7], "brand_id": 1},
  {"name": "Mortadela 100g", "category_id": [1, 7], "brand_id": 45},
  {"name": "Mortadela 100g", "category_id": [1, 7], "brand_id": 46},
  {"name": "Margarina 250g", "category_id": [1, 7], "brand_id": 126},
  {"name": "Margarina 500g", "category_id": [1, 7], "brand_id": 126},
  {"name": "Margarina 250g", "category_id": [1, 7], "brand_id": 127},
  {"name": "Margarina 500g", "category_id": [1, 7], "brand_id": 127},
  {"name": "Margarina 250g", "category_id": [1, 7], "brand_id": 128},
  {"name": "Margarina 500g", "category_id": [1, 7], "brand_id": 128},
  {"name": "Margarina 250g", "category_id": [1, 7], "brand_id": 129},
  {"name": "Margarina 500g", "category_id": [1, 7], "brand_id": 129},
  {"name": "Margarina 250g", "category_id": [1, 7], "brand_id": 130},
  {"name": "Margarina 500g", "category_id": [1, 7], "brand_id": 130},
  {"name": "Manteiga 200g", "category_id": [11, 7], "brand_id": 126},
  {"name": "Requeijão 200g", "category_id": [11, 7], "brand_id": 126},
  {"name": "Requeijão 200g", "category_id": [11, 7], "brand_id": 3},
  {"name": "Requeijão 200g", "category_id": [11, 7], "brand_id": 40},
  {"name": "Requeijão 200g", "category_id": [11, 7], "brand_id": 39},
  {"name": "Iogurte 1,25kg", "category_id": [11, 9, 7], "brand_id": 3},
  {"name": "Iogurte 1,25kg", "category_id": [11, 9, 7], "brand_id": 39},
  {"name": "Iogurte 1,25kg", "category_id": [11, 9, 7], "brand_id": 40},
  {"name": "Iogurte 1,25kg", "category_id": [11, 9, 7], "brand_id": 41},
  {"name": "Leite 1L", "category_id": [11, 9, 7], "brand_id": 10},
  {"name": "Leite 1L", "category_id": [11, 9, 7], "brand_id": 11},
  {"name": "Leite 1L", "category_id": [11, 9, 7], "brand_id": 29},
  {"name": "Leite 1L", "category_id": [11, 9, 7], "brand_id": 42},
  {"name": "Leite Condensado 395g", "category_id": [11, 7], "brand_id": 3},
  {"name": "Leite Condensado 395g", "category_id": [11, 7], "brand_id": 10},
  {"name": "Leite Condensado 395g", "category_id": [11, 7], "brand_id": 42},
  {"name": "Creme de Leite 200g", "category_id": [11, 7], "brand_id": 3},
  {"name": "Creme de Leite 200g", "category_id": [11, 7], "brand_id": 10},
  {"name": "Creme de Leite 200g", "category_id": [11, 7], "brand_id": 42},
  {"name": "Achocolatado em Pó 200g", "category_id": [7], "brand_id": 28},
  {"name": "Achocolatado 200ml", "category_id": [11, 9, 7], "brand_id": 26},
  {"name": "Achocolatado 200ml", "category_id": [11, 9, 7], "brand_id": 27},
  {"name": "Achocolatado 200ml", "category_id": [11, 9, 7], "brand_id": 28},
  {"name": "Café 500g", "category_id": [19, 7], "brand_id": 34},
  {"name": "Café 500g", "category_id": [19, 7], "brand_id": 35},
  {"name": "Café 500g", "category_id": [19, 7], "brand_id": 36},
  {"name": "Café 500g", "category_id": [19, 7], "brand_id": 37},
  {"name": "Café 500g", "category_id": [19, 7], "brand_id": 38},
  {"name": "Café 250g", "category_id": [19, 7], "brand_id": 34},
  {"name": "Café 250g", "category_id": [19, 7], "brand_id": 35},
  {"name": "Café 250g", "category_id": [19, 7], "brand_id": 36},
  {"name": "Café 250g", "category_id": [19, 7], "brand_id": 37},
  {"name": "Café 250g", "category_id": [19, 7], "brand_id": 38},
  {"name": "Banana Prata 100g", "category_id": [6], "brand_id": 1},
  {"name": "Maçã 100g", "category_id": [6], "brand_id": 1},
  {"name": "Uva Vermelha 500g", "category_id": [6], "brand_id": 1},
  {"name": "Uva Verde 500g", "category_id": [6], "brand_id": 1},
  {"name": "Morango 250g", "category_id": [6], "brand_id": 1},
  {"name": "Melancia", "category_id": [6], "brand_id": 1},
  {"name": "Melão", "category_id": [6], "brand_id": 1},
  {"name": "Abacaxi", "category_id": [6], "brand_id": 1},
  {"name": "Laranja 100g", "category_id": [6], "brand_id": 1},
  {"name": "Limão 100g", "category_id": [6], "brand_id": 1},
  {"name": "Manga 100g", "category_id": [6], "brand_id": 1},
  {"name": "Pera 100g", "category_id": [6], "brand_id": 1},
  {"name": "Pêssego 100g", "category_id": [6], "brand_id": 1},
  {"name": "Ameixa 100g", "category_id": [6], "brand_id": 1},
  {"name": "Kiwi 100g", "category_id": [6], "brand_id": 1},
  {"name": "Cenoura 100g", "category_id": [6], "brand_id": 1},
  {"name": "Beterraba 100g", "category_id": [6], "brand_id": 1},
  {"name": "Batata 100g", "category_id": [6], "brand_id": 1},
  {"name": "Batata Doce 100g", "category_id": [6], "brand_id": 1},
  {"name": "Batata Inglesa 100g", "category_id": [6], "brand_id": 1},
  {"name": "Mandioca 100g", "category_id": [6], "brand_id": 1},
  {"name": "Inhame 100g", "category_id": [6], "brand_id": 1},
  {"name": "Abóbora", "category_id": [6], "brand_id": 1},
  {"name": "Abobrinha", "category_id": [6], "brand_id": 1},
  {"name": "Chuchu", "category_id": [6], "brand_id": 1},
  {"name": "Pepino 100g", "category_id": [6], "brand_id": 1},
  {"name": "Tomate 100g", "category_id": [6], "brand_id": 1},
  {"name": "Alface", "category_id": [6], "brand_id": 1},
  {"name": "Repolho", "category_id": [6], "brand_id": 1},
  {"name": "Couve", "category_id": [6], "brand_id": 1},
  {"name": "Rúcula", "category_id": [6], "brand_id": 1},
  {"name": "Agrião", "category_id": [6], "brand_id": 1},
  {"name": "Espinafre", "category_id": [6], "brand_id": 1},
  {"name": "Brócolis", "category_id": [6], "brand_id": 1},
  {"name": "Couve-Flor", "category_id": [6], "brand_id": 1},
  {"name": "Berinjela", "category_id": [6], "brand_id": 1},
  {"name": "Pimentão 100g", "category_id": [6], "brand_id": 1},
  {"name": "Cebola 100g", "category_id": [6], "brand_id": 1},
  {"name": "Alho 100g", "category_id": [6], "brand_id": 1},
  {"name": "Gengibre 100g", "category_id": [6], "brand_id": 1},
  {"name": "Cebolinha 100g", "category_id": [6], "brand_id": 1},
  {"name": "Salsinha 100g", "category_id": [6], "brand_id": 1},
  {"name": "Coentro 100g", "category_id": [6], "brand_id": 1},
  {"name": "Manjericão 100g", "category_id": [6], "brand_id": 1},
  {"name": "Hortelã 100g", "category_id": [6], "brand_id": 1},
  {"name": "Alecrim 100g", "category_id": [6], "brand_id": 1},
  {"name": "Tomilho 100g", "category_id": [6], "brand_id": 1},
  {"name": "Orégano 100g", "category_id": [6], "brand_id": 1},
  {"name": "Sálvia 100g", "category_id": [6], "brand_id": 1},
  {"name": "Fermento Químico 100g", "category_id": [6], "brand_id": 1},
  {"name": "Fermento Biológico 100g", "category_id": [6], "brand_id": 1},
  {"name": "Farinha de Trigo 1kg", "category_id": [8, 6], "brand_id": 2},
  {"name": "Farinha de Rosca 1kg", "category_id": [8, 6], "brand_id": 1},
  {"name": "Farinha de Mandioca 1kg", "category_id": [8, 6], "brand_id": 1},
  {"name": "Arroz Agulha Tipo 1 1kg", "category_id": [8], "brand_id": 93},
  {"name": "Arroz Agulha Tipo 1 2kg", "category_id": [8], "brand_id": 93},
  {"name": "Arroz Agulha Tipo 1 5kg", "category_id": [8], "brand_id": 93},
  {"name": "Arroz Agulha Tipo 1 1kg", "category_id": [8], "brand_id": 69},
  {"name": "Arroz Agulha Tipo 1 2kg", "category_id": [8], "brand_id": 69},
  {"name": "Arroz Agulha Tipo 1 5kg", "category_id": [8], "brand_id": 69},
  {"name": "Arroz Agulha Tipo 1 1kg", "category_id": [8], "brand_id": 70},
  {"name": "Arroz Agulha Tipo 1 2kg", "category_id": [8], "brand_id": 70},
  {"name": "Arroz Agulha Tipo 1 5kg", "category_id": [8], "brand_id": 70},
  {"name": "Arroz Integral 1kg", "category_id": [8], "brand_id": 93},
  {"name": "Arroz Integral 2kg", "category_id": [8], "brand_id": 93},
  {"name": "Arroz Integral 5kg", "category_id": [8], "brand_id": 93},
  {"name": "Arroz Integral 1kg", "category_id": [8], "brand_id": 69},
  {"name": "Arroz Integral 2kg", "category_id": [8], "brand_id": 69},
  {"name": "Arroz Integral 5kg", "category_id": [8], "brand_id": 69},
  {"name": "Arroz Integral 1kg", "category_id": [8], "brand_id": 70},
  {"name": "Arroz Integral 2kg", "category_id": [8], "brand_id": 70},
  {"name": "Arroz Integral 5kg", "category_id": [8], "brand_id": 70},
  {"name": "Feijão Preto 1kg", "category_id": [8], "brand_id": 93},
  {"name": "Feijão Preto 1kg", "category_id": [8], "brand_id": 70},
  {"name": "Feijão Preto 1kg", "category_id": [8], "brand_id": 71},
  {"name": "Feijão Carioca 1kg", "category_id": [8], "brand_id": 93},
  {"name": "Feijão Carioca 1kg", "category_id": [8], "brand_id": 70},
  {"name": "Feijão Carioca 1kg", "category_id": [8], "brand_id": 71},
  {"name": "Refrigerante 350ml", "category_id": [9], "brand_id": 12},
  {"name": "Refrigerante 350ml", "category_id": [9], "brand_id": 13},
  {"name": "Refrigerante 350ml", "category_id": [9], "brand_id": 14},
  {"name": "Refrigerante 350ml", "category_id": [9], "brand_id": 15},
  {"name": "Refrigerante de Uva 350ml", "category_id": [9], "brand_id": 16},
  {"name": "Refrigerante de Laranja 350ml", "category_id": [9], "brand_id": 16},
  {"name": "Refrigerante 350ml", "category_id": [9], "brand_id": 17},
  {"name": "Refrigerante 600ml", "category_id": [9], "brand_id": 12},
  {"name": "Refrigerante 600ml", "category_id": [9], "brand_id": 13},
  {"name": "Refrigerante 600ml", "category_id": [9], "brand_id": 14},
  {"name": "Refrigerante 600ml", "category_id": [9], "brand_id": 15},
  {"name": "Refrigerante de Uva 600ml", "category_id": [9], "brand_id": 16},
  {"name": "Refrigerante de Laranja 600ml", "category_id": [9], "brand_id": 16},
  {"name": "Refrigerante 600ml", "category_id": [9], "brand_id": 17},
  {"name": "Refrigerante 1L", "category_id": [9], "brand_id": 12},
  {"name": "Refrigerante 1L", "category_id": [9], "brand_id": 13},
  {"name": "Refrigerante 1L", "category_id": [9], "brand_id": 14},
  {"name": "Refrigerante 1L", "category_id": [9], "brand_id": 15},
  {"name": "Refrigerante de Uva 1L", "category_id": [9], "brand_id": 16},
  {"name": "Refrigerante de Laranja 1L", "category_id": [9], "brand_id": 16},
  {"name": "Refrigerante 1L", "category_id": [9], "brand_id": 17},
  {"name": "Refrigerante 1,5L", "category_id": [9], "brand_id": 12},
  {"name": "Refrigerante 1,5L", "category_id": [9], "brand_id": 13},
  {"name": "Refrigerante 1,5L", "category_id": [9], "brand_id": 14},
  {"name": "Refrigerante 1,5L", "category_id": [9], "brand_id": 15},
  {"name": "Refrigerante de Uva 1,5L", "category_id": [9], "brand_id": 16},
  {"name": "Refrigerante de Laranja 1,5L", "category_id": [9], "brand_id": 16},
  {"name": "Refrigerante 1,5L", "category_id": [9], "brand_id": 17},
  {"name": "Refrigerante 2L", "category_id": [9], "brand_id": 12},
  {"name": "Refrigerante 2L", "category_id": [9], "brand_id": 13},
  {"name": "Refrigerante 2L", "category_id": [9], "brand_id": 14},
  {"name": "Refrigerante 2L", "category_id": [9], "brand_id": 15},
  {"name": "Refrigerante de Uva 2L", "category_id": [9], "brand_id": 16},
  {"name": "Refrigerante de Laranja 2L", "category_id": [9], "brand_id": 16},
  {"name": "Refrigerante 2L", "category_id": [9], "brand_id": 17},
  {"name": "Refrigerante 2,5L", "category_id": [9], "brand_id": 12},
  {"name": "Refrigerante 2,5L", "category_id": [9], "brand_id": 13},
  {"name": "Refrigerante 2,5L", "category_id": [9], "brand_id": 14},
  {"name": "Refrigerante 2,5L", "category_id": [9], "brand_id": 15},
  {"name": "Refrigerante de Uva 2,5L", "category_id": [9], "brand_id": 16},
  {"name": "Refrigerante de Laranja 2,5L", "category_id": [9], "brand_id": 16},
  {"name": "Refrigerante 2,5L", "category_id": [9], "brand_id": 17},
  {"name": "Refrigerante 3L", "category_id": [9], "brand_id": 12},
  {"name": "Refrigerante 3L", "category_id": [9], "brand_id": 13},
  {"name": "Refrigerante 3L", "category_id": [9], "brand_id": 14},
  {"name": "Refrigerante 3L", "category_id": [9], "brand_id": 15},
  {"name": "Refrigerante de Uva 3L", "category_id": [9], "brand_id": 16},
  {"name": "Refrigerante de Laranja 3L", "category_id": [9], "brand_id": 16},
  {"name": "Refrigerante 3L", "category_id": [9], "brand_id": 17},
  {"name": "Suco de Uva 1L", "category_id": [9], "brand_id": 23},
  {"name": "Suco de Uva 1L", "category_id": [9], "brand_id": 24},
  {"name": "Suco de Uva 1L", "category_id": [9], "brand_id": 25},
  {"name": "Suco de Laranja 1L", "category_id": [9], "brand_id": 23},
  {"name": "Suco de Laranja 1L", "category_id": [9], "brand_id": 24},
  {"name": "Suco de Laranja 1L", "category_id": [9], "brand_id": 25},
  {"name": "Suco de Pêssego 1L", "category_id": [9], "brand_id": 23},
  {"name": "Suco de Pêssego 1L", "category_id": [9], "brand_id": 24},
  {"name": "Suco de Pêssego 1L", "category_id": [9], "brand_id": 25},
  {"name": "Suco de Manga 1L", "category_id": [9], "brand_id": 23},
  {"name": "Suco de Manga 1L", "category_id": [9], "brand_id": 24},
  {"name": "Suco de Manga 1L", "category_id": [9], "brand_id": 25},
  {"name": "Suco de Maçã 1L", "category_id": [9], "brand_id": 23},
  {"name": "Suco de Maçã 1L", "category_id": [9], "brand_id": 24},
  {"name": "Suco de Maçã 1L", "category_id": [9], "brand_id": 25},
  {"name": "Água Mineral 500ml", "category_id": [9], "brand_id": 18},
  {"name": "Água Mineral 500ml", "category_id": [9], "brand_id": 19},
  {"name": "Água Mineral 500ml", "category_id": [9], "brand_id": 20},
  {"name": "Água Mineral 500ml", "category_id": [9], "brand_id": 21},
  {"name": "Água Mineral 1,5L", "category_id": [9], "brand_id": 18},
  {"name": "Água Mineral 1,5L", "category_id": [9], "brand_id": 19},
  {"name": "Água Mineral 1,5L", "category_id": [9], "brand_id": 20},
  {"name": "Água Mineral 1,5L", "category_id": [9], "brand_id": 21},
  {"name": "Chá", "category_id": [9], "brand_id": 22},
  {"name": "Cerveja 350ml", "category_id": [9], "brand_id": 57},
  {"name": "Cerveja 350ml", "category_id": [9], "brand_id": 58},
  {"name": "Cerveja 350ml", "category_id": [9], "brand_id": 59},
  {"name": "Cerveja 350ml", "category_id": [9], "brand_id": 60},
  {"name": "Cerveja 350ml", "category_id": [9], "brand_id": 61},
  {"name": "Cerveja 350ml", "category_id": [9], "brand_id": 62},
  {"name": "Energético 250ml", "category_id": [9], "brand_id": 63},
  {"name": "Energético 473ml", "category_id": [9], "brand_id": 64},
  {"name": "Detergente 500ml", "category_id": [10], "brand_id": 115},
  {"name": "Detergente 500ml", "category_id": [10], "brand_id": 117},
  {"name": "Sabonete", "category_id": [10], "brand_id": 75},
  {"name": "Sabonete", "category_id": [10], "brand_id": 76},
  {"name": "Sabonete", "category_id": [10], "brand_id": 77},
  {"name": "Sabonete", "category_id": [10], "brand_id": 78},
  {"name": "Sabonete", "category_id": [10], "brand_id": 116},
  {"name": "Shampoo", "category_id": [10], "brand_id": 79},
  {"name": "Shampoo", "category_id": [10], "brand_id": 80},
  {"name": "Shampoo", "category_id": [10], "brand_id": 81},
  {"name": "Shampoo", "category_id": [10], "brand_id": 82},
  {"name": "Shampoo", "category_id": [10], "brand_id": 83},
  {"name": "Condicionador", "category_id": [10], "brand_id": 79},
  {"name": "Condicionador", "category_id": [10], "brand_id": 80},
  {"name": "Condicionador", "category_id": [10], "brand_id": 81},
  {"name": "Condicionador", "category_id": [10], "brand_id": 82},
  {"name": "Condicionador", "category_id": [10], "brand_id": 83},
  {"name": "Papel Higiênico 4un", "category_id": [10], "brand_id": 85},
  {"name": "Papel Higiênico 4un", "category_id": [10], "brand_id": 86},
  {"name": "Papel Higiênico 4un", "category_id": [10], "brand_id": 87},
  {"name": "Papel Higiênico 12un", "category_id": [10], "brand_id": 85},
  {"name": "Papel Higiênico 12un", "category_id": [10], "brand_id": 86},
  {"name": "Papel Higiênico 12un", "category_id": [10], "brand_id": 87},
  {"name": "Papel Higiênico 24un", "category_id": [10], "brand_id": 85},
  {"name": "Papel Higiênico 24un", "category_id": [10], "brand_id": 86},
  {"name": "Papel Higiênico 24un", "category_id": [10], "brand_id": 87},
  {"name": "Pasta de Dente 90g", "category_id": [10], "brand_id": 132},
  {"name": "Pasta de Dente 90g", "category_id": [10], "brand_id": 133},
  {"name": "Pasta de Dente 90g", "category_id": [10], "brand_id": 134},
  {"name": "Amaciante 2L", "category_id": [10], "brand_id": 108},
  {"name": "Amaciante 2L", "category_id": [10], "brand_id": 109},
  {"name": "Amaciante 2L", "category_id": [10], "brand_id": 110},
  {"name": "Amaciante 2L", "category_id": [10], "brand_id": 111},
  {"name": "Amaciante 2L", "category_id": [10], "brand_id": 112},
  {"name": "Amaciante 2L", "category_id": [10], "brand_id": 113},
  {"name": "Amaciante 2L", "category_id": [10], "brand_id": 114},
  {"name": "Sabão em Pó 2,2kg", "category_id": [10], "brand_id": 110},
  {"name": "Sabão em Pó 2,2kg", "category_id": [10], "brand_id": 112},
  {"name": "Sabão Líquido 3L", "category_id": [10], "brand_id": 110},
  {"name": "Sabão Líquido 3L", "category_id": [10], "brand_id": 112},
  {"name": "Desinfetante 2L", "category_id": [10], "brand_id": 115},
  {"name": "Água Sanitária 1L", "category_id": [10], "brand_id": 1},
  {"name": "Água Sanitária 2L", "category_id": [10], "brand_id": 1},
  {"name": "Água Sanitária 5L", "category_id": [10], "brand_id": 1},
  {"name": "Lustra Móveis 200ml", "category_id": [10], "brand_id": 1},
  {"name": "Limpa Vidros 500ml", "category_id": [10], "brand_id": 1},
  {"name": "Esponja de Aço 8un", "category_id": [10], "brand_id": 118},
  {"name": "Desengordurante 500ml", "category_id": [10], "brand_id": 1},
  {"name": "Fio Dental 50m", "category_id": [10], "brand_id": 1},
  {"name": "Pizza Bolonhesa 460g", "category_id": [12], "brand_id": 45},
  {"name": "Pizza Bolonhesa 460g", "category_id": [12], "brand_id": 46},
  {"name": "Pizza Bolonhesa 460g", "category_id": [12], "brand_id": 47},
  {"name": "Pizza Bolonhesa 460g", "category_id": [12], "brand_id": 49},
  {"name": "Pizza Bolonhesa 460g", "category_id": [12], "brand_id": 50},
  {"name": "Pizza de Frango 460g", "category_id": [12], "brand_id": 45},
  {"name": "Pizza de Frango 460g", "category_id": [12], "brand_id": 46},
  {"name": "Pizza de Frango 460g", "category_id": [12], "brand_id": 47},
  {"name": "Pizza de Frango 460g", "category_id": [12], "brand_id": 49},
  {"name": "Pizza de Frango 460g", "category_id": [12], "brand_id": 50},
  {"name": "Pizza 4 Queijos 460g", "category_id": [12], "brand_id": 45},
  {"name": "Pizza 4 Queijos 460g", "category_id": [12], "brand_id": 46},
  {"name": "Pizza 4 Queijos 460g", "category_id": [12], "brand_id": 47},
  {"name": "Pizza 4 Queijos 460g", "category_id": [12], "brand_id": 49},
  {"name": "Pizza 4 Queijos 460g", "category_id": [12], "brand_id": 50},
  {"name": "Pizza Calabresa 460g", "category_id": [12], "brand_id": 45},
  {"name": "Pizza Calabresa 460g", "category_id": [12], "brand_id": 46},
  {"name": "Pizza Calabresa 460g", "category_id": [12], "brand_id": 47},
  {"name": "Pizza Calabresa 460g", "category_id": [12], "brand_id": 49},
  {"name": "Pizza Calabresa 460g", "category_id": [12], "brand_id": 50},
  {"name": "Lasanha Bolonhesa 600g", "category_id": [12], "brand_id": 45},
  {"name": "Lasanha Bolonhesa 600g", "category_id": [12], "brand_id": 46},
  {"name": "Lasanha Bolonhesa 600g", "category_id": [12], "brand_id": 47},
  {"name": "Lasanha Bolonhesa 600g", "category_id": [12], "brand_id": 49},
  {"name": "Lasanha Bolonhesa 600g", "category_id": [12], "brand_id": 50},
  {"name": "Lasanha de Frango 600g", "category_id": [12], "brand_id": 45},
  {"name": "Lasanha de Frango 600g", "category_id": [12], "brand_id": 46},
  {"name": "Lasanha de Frango 600g", "category_id": [12], "brand_id": 47},
  {"name": "Lasanha de Frango 600g", "category_id": [12], "brand_id": 49},
  {"name": "Lasanha de Frango 600g", "category_id": [12], "brand_id": 50},
  {"name": "Lasanha 4 Queijos 600g", "category_id": [12], "brand_id": 45},
  {"name": "Lasanha 4 Queijos 600g", "category_id": [12], "brand_id": 46},
  {"name": "Lasanha 4 Queijos 600g", "category_id": [12], "brand_id": 47},
  {"name": "Lasanha 4 Queijos 600g", "category_id": [12], "brand_id": 49},
  {"name": "Lasanha 4 Queijos 600g", "category_id": [12], "brand_id": 50},
  {"name": "Lasanha Calabresa 600g", "category_id": [12], "brand_id": 45},
  {"name": "Lasanha Calabresa 600g", "category_id": [12], "brand_id": 46},
  {"name": "Lasanha Calabresa 600g", "category_id": [12], "brand_id": 47},
  {"name": "Lasanha Calabresa 600g", "category_id": [12], "brand_id": 49},
  {"name": "Lasanha Calabresa 600g", "category_id": [12], "brand_id": 50},
  {"name": "Hamburguer de Carne 12 unidades", "category_id": [12], "brand_id": 45},
  {"name": "Hamburguer de Carne 12 unidades", "category_id": [12], "brand_id": 46},
  {"name": "Hamburguer de Carne 12 unidades", "category_id": [12], "brand_id": 47},
  {"name": "Hamburguer de Carne 12 unidades", "category_id": [12], "brand_id": 48},
  {"name": "Hamburguer de Carne 12 unidades", "category_id": [12], "brand_id": 49},
  {"name": "Hamburguer de Carne 12 unidades", "category_id": [12], "brand_id": 50},
  {"name": "Hamburguer de Carne 12 unidades", "category_id": [12], "brand_id": 51},
  {"name": "Hamburguer de Frango 12 unidades", "category_id": [12], "brand_id": 45},
  {"name": "Hamburguer de Frango 12 unidades", "category_id": [12], "brand_id": 46},
  {"name": "Hamburguer de Frango 12 unidades", "category_id": [12], "brand_id": 47},
  {"name": "Hamburguer de Frango 12 unidades", "category_id": [12], "brand_id": 48},
  {"name": "Hamburguer de Frango 12 unidades", "category_id": [12], "brand_id": 49},
  {"name": "Hamburguer de Frango 12 unidades", "category_id": [12], "brand_id": 50},
  {"name": "Hamburguer de Frango 12 unidades", "category_id": [12], "brand_id": 51},
  {"name": "Hamburguer Misto 12 unidades", "category_id": [12], "brand_id": 45},
  {"name": "Hamburguer Misto 12 unidades", "category_id": [12], "brand_id": 46},
  {"name": "Hamburguer Misto 12 unidades", "category_id": [12], "brand_id": 47},
  {"name": "Hamburguer Misto 12 unidades", "category_id": [12], "brand_id": 48},
  {"name": "Hamburguer Misto 12 unidades", "category_id": [12], "brand_id": 49},
  {"name": "Hamburguer Misto 12 unidades", "category_id": [12], "brand_id": 50},
  {"name": "Hamburguer Misto 12 unidades", "category_id": [12], "brand_id": 51},
  {"name": "Chocolate ao Leite 90g", "category_id": [13], "brand_id": 52},
  {"name": "Chocolate ao Leite 90g", "category_id": [13], "brand_id": 53},
  {"name": "Chocolate ao Leite 90g", "category_id": [13], "brand_id": 54},
  {"name": "Chocolate ao Leite 90g", "category_id": [13], "brand_id": 55},
  {"name": "Chocolate ao Leite 90g", "category_id": [13], "brand_id": 56},
  {"name": "Chocolate Branco 90g", "category_id": [13], "brand_id": 52},
  {"name": "Chocolate Branco 90g", "category_id": [13], "brand_id": 53},
  {"name": "Chocolate Branco 90g", "category_id": [13], "brand_id": 54},
  {"name": "Chocolate Branco 90g", "category_id": [13], "brand_id": 55},
  {"name": "Chocolate Branco 90g", "category_id": [13], "brand_id": 56},
  {"name": "Ração para Cães 1kg", "category_id": [15], "brand_id": 88},
  {"name": "Ração para Cães 1kg", "category_id": [15], "brand_id": 89},
  {"name": "Ração para Cães 1kg", "category_id": [15], "brand_id": 90},
  {"name": "Ração para Cães 1kg", "category_id": [15], "brand_id": 91},
  {"name": "Ração para Gatos 1kg", "category_id": [15], "brand_id": 88},
  {"name": "Ração para Gatos 1kg", "category_id": [15], "brand_id": 92},
  {"name": "Ração para Cães 5kg", "category_id": [15], "brand_id": 88},
  {"name": "Ração para Cães 5kg", "category_id": [15], "brand_id": 89},
  {"name": "Ração para Cães 5kg", "category_id": [15], "brand_id": 90},
  {"name": "Ração para Cães 5kg", "category_id": [15], "brand_id": 91},
  {"name": "Ração para Gatos 5kg", "category_id": [15], "brand_id": 88},
  {"name": "Ração para Gatos 5kg", "category_id": [15], "brand_id": 92},
  {"name": "Ração para Cães 10kg", "category_id": [15], "brand_id": 88},
  {"name": "Ração para Cães 10kg", "category_id": [15], "brand_id": 89},
  {"name": "Ração para Cães 10kg", "category_id": [15], "brand_id": 90},
  {"name": "Ração para Cães 10kg", "category_id": [15], "brand_id": 91},
  {"name": "Ração para Gatos 10kg", "category_id": [15], "brand_id": 88},
  {"name": "Ração para Gatos 10kg", "category_id": [15], "brand_id": 92},
  {"name": "Ração para Cães 15kg", "category_id": [15], "brand_id": 88},
  {"name": "Ração para Cães 15kg", "category_id": [15], "brand_id": 89},
  {"name": "Ração para Cães 15kg", "category_id": [15], "brand_id": 90},
  {"name": "Ração para Cães 15kg", "category_id": [15], "brand_id": 91},
  {"name": "Ração para Gatos 15kg", "category_id": [15], "brand_id": 88},
  {"name": "Ração para Gatos 15kg", "category_id": [15], "brand_id": 92},
  {"name": "Biscoito Recheado", "category_id": [16], "brand_id": 2},
  {"name": "Biscoito Recheado", "category_id": [16], "brand_id": 3},
  {"name": "Biscoito Recheado", "category_id": [16], "brand_id": 4},
  {"name": "Biscoito Recheado", "category_id": [16], "brand_id": 5},
  {"name": "Biscoito Recheado", "category_id": [16], "brand_id": 6},
  {"name": "Biscoito Recheado", "category_id": [16], "brand_id": 7},
  {"name": "Biscoito Recheado", "category_id": [16], "brand_id": 8},
  {"name": "Biscoito Recheado", "category_id": [16], "brand_id": 9},
  {"name": "Biscoito Salgado", "category_id": [16], "brand_id": 3},
  {"name": "Biscoito Salgado", "category_id": [16], "brand_id": 5},
  {"name": "Biscoito Salgado", "category_id": [16], "brand_id": 6},
  {"name": "Biscoito Salgado", "category_id": [16], "brand_id": 7},
  {"name": "Biscoito Salgado", "category_id": [16], "brand_id": 8}
]
